[package]
name = "fortgate_id_proto"
type = "bin"
authors = ["Fortgate ID Engineering"]
compiler_version = ">=0.31.0"

[dependencies]
std = { tag = "v0.31.0" }
rsa = { git = "https://github.com/noir-lang/noir-rsa", tag = "v0.1.0" }
